---
abstract: 'Easily integrate Peoplesign CAPTCHA in your Perl application'
author:
  - 'Michele Beltrame <mb@italpro.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Captcha-Peoplesign
requires:
  HTML::Tiny: 1.05
  LWP::UserAgent: 5.835
version: 0.00003
